#!/usr/bin/perl

use strict;
use warnings;

use FindBin '$Bin';
use lib "$Bin/lib";
use Getopt::Long;
use SchwartzMan::Worker;
use Gearman::Worker;
use JSON;

my %o = ();

# TODO: Doesn't support specifying multiple DB's yet. YAML config or whatever?
# TODO: Uhh... require a control manager or do our own fork management?
GetOptions(\%o,
    'gearmand=s@',
    'dsn=s',
    'username=s',
    'password=s',
    );

die "Need dsn" unless $o{dsn};

my $work_helper;
my $count = 0;
run();

sub run {
    $work_helper = SchwartzMan::Worker->new(
        dbs => {1 => { id => 1, dsn => $o{dsn}, user => $o{username},
        pass => $o{password}, }},
        );

    my $worker = Gearman::Worker->new;
    $worker->job_servers(@{$o{gearmand}});
    $worker->register_function('foo' => \&consume_thing);
    $worker->work;
}

sub consume_thing {
    my $job = decode_json(${$_[0]->argref});
    print "Hay it's a job: ", $job->{arg}, "\n" if $count++ % 100 == 0;
    $work_helper->complete_job($job);
}
